# DO NOT EDIT THIS FILE

SUBMIT      := imp.ml queueTest.ml linkedQueue.ml simpleQueue.ml dequeTest.ml deque.ml graph.ml

DEPENDS := \
	assert.ml \
	assert.mli \
	queueInterface.ml \
	queueInterface.mli \
	imp.ml \
	imp.mli \
	queueTest.ml \
	linkedQueue.ml \
	linkedQueue.mli \
	simpleQueue.ml \
	simpleQueue.mli \
	dequeTest.ml \
	deque.ml \
	deque.mli \
	graph.ml \
	graph.mli 


SHELL := /bin/bash

HWNAME := hw04
ts := $(shell /bin/date "+%Y-%m-%d-%H:%M:%S")

ZIPNAME := $(HWNAME)-submit($(ts)).zip

.PHONY: all  clean zip

all:	imp.byte queueTest.byte linkedQueue.byte simpleQueue.byte dequeTest.byte deque.byte graph.byte

%.byte: $(DEPENDS)
	ocamlbuild -r -tag debug -libs unix,str  $@

run% : %.byte $(DEPENDS)
	OCAMLRUNPARAM=b _build/$<

zip: $(SUBMIT)
	zip '$(ZIPNAME)' $(SUBMIT)

clean:
	ocamlbuild -clean
	rm -rf *.zip

format:

utop: 
	ocamlbuild assert.cmo imp.cmo queueTest.cmo linkedQueue.cmo simpleQueue.cmo \
	deque.cmo dequeTest.cmo graph.cmo queueInterface.cmo
